[package]
name = "oidc-service-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
color-eyre = "0.6.3"
env_logger = "0.11.5"
git-oidc = { path = "../git-oidc" }
log = "0.4.22"
serde = "1.0.209"
serde_json = "1.0.127"
tokio = "1.39.3"
